name: Build and Push Docker Image

on:
  push:
    branches:
      - 'master'
      - 'main'
  #    tags:
  #      - '*'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  OWNER: amindentalcenter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Metadata
        uses: docker/metadata-action@v5
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to GitHub Container Registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push Docker image Master
        if: github.ref == 'refs/heads/master'
        id: build-and-push-master-latest
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./rootfs/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ steps.meta.outputs.tags }}

      - name: Build and push Docker image for Branches
        id: build-and-push-release
        uses: docker/build-push-action@v4
        with:
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}